# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\x04\x64\x65mo\"\x1c\n\x0cUnaryRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rUnaryResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\x16ServerStreamingRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\":\n\x17ServerStreamingResponse\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\'\n\x16\x43lientStreamingRequest\x12\r\n\x05value\x18\x01 \x01(\x05\"5\n\x17\x43lientStreamingResponse\x12\x0b\n\x03sum\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"\'\n\x14\x42idirectionalRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"7\n\x15\x42idirectionalResponse\x12\x0c\n\x04\x65\x63ho\x18\x01 \x01(\t\x12\x10\n\x08sequence\x18\x02 \x01(\x05\x32\xca\x02\n\x0b\x44\x65moService\x12\x34\n\tUnaryCall\x12\x12.demo.UnaryRequest\x1a\x13.demo.UnaryResponse\x12T\n\x13ServerStreamingCall\x12\x1c.demo.ServerStreamingRequest\x1a\x1d.demo.ServerStreamingResponse0\x01\x12T\n\x13\x43lientStreamingCall\x12\x1c.demo.ClientStreamingRequest\x1a\x1d.demo.ClientStreamingResponse(\x01\x12Y\n\x1a\x42idirectionalStreamingCall\x12\x1a.demo.BidirectionalRequest\x1a\x1b.demo.BidirectionalResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UNARYREQUEST']._serialized_start=20
  _globals['_UNARYREQUEST']._serialized_end=48
  _globals['_UNARYRESPONSE']._serialized_start=50
  _globals['_UNARYRESPONSE']._serialized_end=82
  _globals['_SERVERSTREAMINGREQUEST']._serialized_start=84
  _globals['_SERVERSTREAMINGREQUEST']._serialized_end=123
  _globals['_SERVERSTREAMINGRESPONSE']._serialized_start=125
  _globals['_SERVERSTREAMINGRESPONSE']._serialized_end=183
  _globals['_CLIENTSTREAMINGREQUEST']._serialized_start=185
  _globals['_CLIENTSTREAMINGREQUEST']._serialized_end=224
  _globals['_CLIENTSTREAMINGRESPONSE']._serialized_start=226
  _globals['_CLIENTSTREAMINGRESPONSE']._serialized_end=279
  _globals['_BIDIRECTIONALREQUEST']._serialized_start=281
  _globals['_BIDIRECTIONALREQUEST']._serialized_end=320
  _globals['_BIDIRECTIONALRESPONSE']._serialized_start=322
  _globals['_BIDIRECTIONALRESPONSE']._serialized_end=377
  _globals['_DEMOSERVICE']._serialized_start=380
  _globals['_DEMOSERVICE']._serialized_end=710
# @@protoc_insertion_point(module_scope)
