# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import demo_pb2 as demo__pb2


class DemoServiceStub(object):
    """gRPCの4つの通信方法を定義
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UnaryCall = channel.unary_unary(
                '/demo.DemoService/UnaryCall',
                request_serializer=demo__pb2.UnaryRequest.SerializeToString,
                response_deserializer=demo__pb2.UnaryResponse.FromString,
                )
        self.ServerStreamingCall = channel.unary_stream(
                '/demo.DemoService/ServerStreamingCall',
                request_serializer=demo__pb2.ServerStreamingRequest.SerializeToString,
                response_deserializer=demo__pb2.ServerStreamingResponse.FromString,
                )
        self.ClientStreamingCall = channel.stream_unary(
                '/demo.DemoService/ClientStreamingCall',
                request_serializer=demo__pb2.ClientStreamingRequest.SerializeToString,
                response_deserializer=demo__pb2.ClientStreamingResponse.FromString,
                )
        self.BidirectionalStreamingCall = channel.stream_stream(
                '/demo.DemoService/BidirectionalStreamingCall',
                request_serializer=demo__pb2.BidirectionalRequest.SerializeToString,
                response_deserializer=demo__pb2.BidirectionalResponse.FromString,
                )


class DemoServiceServicer(object):
    """gRPCの4つの通信方法を定義
    """

    def UnaryCall(self, request, context):
        """1. Unary RPC: 単一リクエスト -> 単一レスポンス
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerStreamingCall(self, request, context):
        """2. Server Streaming RPC: 単一リクエスト -> ストリームレスポンス
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientStreamingCall(self, request_iterator, context):
        """3. Client Streaming RPC: ストリームリクエスト -> 単一レスポンス
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BidirectionalStreamingCall(self, request_iterator, context):
        """4. Bidirectional Streaming RPC: ストリームリクエスト <-> ストリームレスポンス
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DemoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UnaryCall': grpc.unary_unary_rpc_method_handler(
                    servicer.UnaryCall,
                    request_deserializer=demo__pb2.UnaryRequest.FromString,
                    response_serializer=demo__pb2.UnaryResponse.SerializeToString,
            ),
            'ServerStreamingCall': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerStreamingCall,
                    request_deserializer=demo__pb2.ServerStreamingRequest.FromString,
                    response_serializer=demo__pb2.ServerStreamingResponse.SerializeToString,
            ),
            'ClientStreamingCall': grpc.stream_unary_rpc_method_handler(
                    servicer.ClientStreamingCall,
                    request_deserializer=demo__pb2.ClientStreamingRequest.FromString,
                    response_serializer=demo__pb2.ClientStreamingResponse.SerializeToString,
            ),
            'BidirectionalStreamingCall': grpc.stream_stream_rpc_method_handler(
                    servicer.BidirectionalStreamingCall,
                    request_deserializer=demo__pb2.BidirectionalRequest.FromString,
                    response_serializer=demo__pb2.BidirectionalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demo.DemoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DemoService(object):
    """gRPCの4つの通信方法を定義
    """

    @staticmethod
    def UnaryCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/demo.DemoService/UnaryCall',
            demo__pb2.UnaryRequest.SerializeToString,
            demo__pb2.UnaryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServerStreamingCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/demo.DemoService/ServerStreamingCall',
            demo__pb2.ServerStreamingRequest.SerializeToString,
            demo__pb2.ServerStreamingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClientStreamingCall(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/demo.DemoService/ClientStreamingCall',
            demo__pb2.ClientStreamingRequest.SerializeToString,
            demo__pb2.ClientStreamingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BidirectionalStreamingCall(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/demo.DemoService/BidirectionalStreamingCall',
            demo__pb2.BidirectionalRequest.SerializeToString,
            demo__pb2.BidirectionalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
