// Autogenerated with StateSmith 0.20.0+43839dcc75301cd62cac3f27a49bbde57af7ebda.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>
#include <stdint.h> // for count var


typedef enum MySm_EventId
{
    MySm_EventId_DIM = 0,
    MySm_EventId_INC = 1,
    MySm_EventId_TOGGLE = 2
} MySm_EventId;

enum
{
    MySm_EventIdCount = 3
};

typedef enum MySm_StateId
{
    MySm_StateId_ROOT = 0,
    MySm_StateId_OFF = 1,
    MySm_StateId_ON_GROUP = 2,
    MySm_StateId_ON1 = 3,
    MySm_StateId_ON2 = 4,
    MySm_StateId_ON3 = 5
} MySm_StateId;

enum
{
    MySm_StateIdCount = 6
};


// Generated state machine
// forward declaration
typedef struct MySm MySm;

// State machine variables. Can be used for inputs, outputs, user variables...
typedef struct MySm_Vars
{
    uint16_t count; // this var can be referenced in diagram
} MySm_Vars;


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void MySm_ctor(MySm* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void MySm_start(MySm* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void MySm_dispatch_event(MySm* sm, MySm_EventId event_id);

// Thread safe.
char const * MySm_state_id_to_string(MySm_StateId id);

// Thread safe.
char const * MySm_event_id_to_string(MySm_EventId id);

// Generated state machine
struct MySm
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    MySm_StateId state_id;
    
    // Variables. Can be used for inputs, outputs, user variables...
    MySm_Vars vars;
};

