# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: usage.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busage.proto\x12\x05usage\"4\n\x0cUsageRequest\x12\x12\n\nstart_time\x18\x01 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x03\"#\n\rUsageResponse\x12\x12\n\ndata_usage\x18\x01 \x01(\x03\x32G\n\x0cUsageService\x12\x37\n\x08GetUsage\x12\x13.usage.UsageRequest\x1a\x14.usage.UsageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USAGEREQUEST']._serialized_start=22
  _globals['_USAGEREQUEST']._serialized_end=74
  _globals['_USAGERESPONSE']._serialized_start=76
  _globals['_USAGERESPONSE']._serialized_end=111
  _globals['_USAGESERVICE']._serialized_start=113
  _globals['_USAGESERVICE']._serialized_end=184
# @@protoc_insertion_point(module_scope)
